
#define IDM_MQTT_LOG_BASE	56000
D(IDM_MQTT_LOG_BASE,	IDM_MQTT_LOG_BASE, 0);
D(IDM_MQTT_LOG_NONE,	IDM_MQTT_LOG_BASE, 0);
D(IDM_MQTT_LOG_INFO,	IDM_MQTT_LOG_BASE, 1);
D(IDM_MQTT_LOG_NOTICE,	IDM_MQTT_LOG_BASE, 2);
D(IDM_MQTT_LOG_WARNING,	IDM_MQTT_LOG_BASE, 3);
D(IDM_MQTT_LOG_ERR,	IDM_MQTT_LOG_BASE, 4);
D(IDM_MQTT_LOG_DEBUG,	IDM_MQTT_LOG_BASE, 5);

#define IDI_MMENU_BASE		57000
D(IDI_MMENU_BASE, IDI_MMENU_BASE, 0);
D(IDI_MMENU_I0,   IDI_MMENU_BASE, 0);
D(IDI_MMENU_I1,   IDI_MMENU_BASE, 1);
D(IDI_MMENU_I2,   IDI_MMENU_BASE, 2);
D(IDI_MMENU_I3,   IDI_MMENU_BASE, 3);
D(IDI_MMENU_I4,   IDI_MMENU_BASE, 4);
D(IDI_MMENU_I6,   IDI_MMENU_BASE, 6);
D(IDI_MMENU_I7,   IDI_MMENU_BASE, 7);
D(IDI_MMENU_I9,   IDI_MMENU_BASE, 9);

#define IDM_PLACE_BASE		58000
D(IDM_PLACE_BASE, IDM_PLACE_BASE, 0);
D(IDM_VERT_LEFT,  IDM_PLACE_BASE, 0);
D(IDM_VERT_RIGHT, IDM_PLACE_BASE, 1);
D(IDM_HOR_TOP,    IDM_PLACE_BASE, 2);
D(IDM_HOR_BOTTOM, IDM_PLACE_BASE, 3);

#define IDM_THEME_BASE		59000
D(IDM_THEME_BASE, IDM_THEME_BASE, 0);
D(IDM_LIGHT,      IDM_THEME_BASE, 0);
D(IDM_DARK,       IDM_THEME_BASE, 1);
D(IDM_METRO,      IDM_THEME_BASE, 2);
D(IDM_MODERN,     IDM_THEME_BASE, 3);
D(IDM_RETRO,      IDM_THEME_BASE, 4);
D(IDM_CUSTOM,     IDM_THEME_BASE, 5);
D(IDM_SAVE_POS,   IDM_THEME_BASE, 6);
D(IDM_CLOSE,      IDM_THEME_BASE, 7);
D(IDM_ANIMATION,  IDM_THEME_BASE, 8);
D(IDM_APP_PATH,   IDM_THEME_BASE, 9);
D(IDM_MIDI_BIND,  IDM_THEME_BASE, 10);
D(IDM_PEAK_METER, IDM_THEME_BASE, 11);
D(IDM_CUSTOM_RELOAD, IDM_THEME_BASE, 12);
