
#define IDS_ERRORID_BASE	30000

/* Common::errors */
D(IDS_ERRORID_BASE,			IDS_ERRORID_BASE, 0)
D(IDS_ERRORID_OK,			IDS_ERRORID_BASE, 0)
D(IDS_ERRORID_EMPTY,			IDS_ERRORID_BASE, 1)
D(IDS_ERRORID_UNDEFINED,		IDS_ERRORID_BASE, 2)

/* Common::json_config */
D(IDS_ERRORID_JSONCONF_WRITE_ACCESS,	IDS_ERRORID_BASE, 3)
D(IDS_ERRORID_JSONCONF_READ_ACCESS,	IDS_ERRORID_BASE, 4)
D(IDS_ERRORID_JSONCONF_EMPTY,		IDS_ERRORID_BASE, 5)
D(IDS_ERRORID_JSONCONF_NO_DEVICE,	IDS_ERRORID_BASE, 6)
D(IDS_ERRORID_JSONCONF_EMPTY_KEYS,	IDS_ERRORID_BASE, 7)
D(IDS_ERRORID_JSONCONF_WRITE_EMPTY,	IDS_ERRORID_BASE, 8)

/* Common::MIXER */
D(IDS_ERRORID_INIT_COINITIALIZE,	IDS_ERRORID_BASE, 9)
D(IDS_ERRORID_INIT_COCREATE,		IDS_ERRORID_BASE, 10)
D(IDS_ERRORID_INIT_DEFAULT_AE,		IDS_ERRORID_BASE, 11)
D(IDS_ERRORID_INIT_AS_MANAGER2,		IDS_ERRORID_BASE, 12)
D(IDS_ERRORID_INIT_AS_AUDIOMETER,	IDS_ERRORID_BASE, 13)
D(IDS_ERRORID_MIXER_STARTOK,		IDS_ERRORID_BASE, 14)
D(IDS_ERRORID_MIXER_STARTERROR,		IDS_ERRORID_BASE, 15)
D(IDS_ERRORID_MIXER_STOPOK,		IDS_ERRORID_BASE, 16)
D(IDS_ERRORID_MIXER_STOPERROR,		IDS_ERRORID_BASE, 17)
D(IDS_ERRORID_NO_INIT,			IDS_ERRORID_BASE, 18)
D(IDS_ERRORID_SESSION_LIST,		IDS_ERRORID_BASE, 19)
D(IDS_ERRORID_LISTISNULL,		IDS_ERRORID_BASE, 20)
D(IDS_ERRORID_SESSIONDISCONNECTED,	IDS_ERRORID_BASE, 21)
D(IDS_ERRORID_SESSIONCREATED,		IDS_ERRORID_BASE, 22)
D(IDS_ERRORID_ITEM_SC_AE,		IDS_ERRORID_BASE, 23)
D(IDS_ERRORID_CBVALUE_BAD_SELECT,	IDS_ERRORID_BASE, 24)

/* Common::MIDI */
D(IDS_ERRORID_SET_CB_WARNING,		IDS_ERRORID_BASE, 25)
D(IDS_ERRORID_CONFIG_FAIL,		IDS_ERRORID_BASE, 26)
D(IDS_ERRORID_CONFIG_LOAD,		IDS_ERRORID_BASE, 27)
D(IDS_ERRORID_CONFIG_LOADA,		IDS_ERRORID_BASE, 28)
D(IDS_ERRORID_CONFIG_EMPTY,		IDS_ERRORID_BASE, 29)
D(IDS_ERRORID_CONFIG_EMPTY_NAME,	IDS_ERRORID_BASE, 30)
D(IDS_ERRORID_CONFIG_NEW,		IDS_ERRORID_BASE, 31)
D(IDS_ERRORID_NOT_IMPLEMENTED,		IDS_ERRORID_BASE, 32)
D(IDS_ERRORID_NOT_CONFIG,		IDS_ERRORID_BASE, 33)
D(IDS_ERRORID_MIDI_NOT_DEVICES,		IDS_ERRORID_BASE, 34)
D(IDS_ERRORID_MIDI_COUNT_DEVICES,	IDS_ERRORID_BASE, 35)
D(IDS_ERRORID_MIDI_OPEN_DEVICE,		IDS_ERRORID_BASE, 36)
D(IDS_ERRORID_MIDI_START_DEVICE,	IDS_ERRORID_BASE, 37)
D(IDS_ERRORID_MIDI_DEVICE_NOT_CONNECT,	IDS_ERRORID_BASE, 38)
D(IDS_ERRORID_MIDI_DEVICE_FOUND,	IDS_ERRORID_BASE, 39)
D(IDS_ERRORID_MIDI_DEVICE_OPEN,		IDS_ERRORID_BASE, 40)
D(IDS_ERRORID_MIDI_DEVICE_CLOSE,	IDS_ERRORID_BASE, 41)
D(IDS_ERRORID_MIDI_DEVICE_DONE,		IDS_ERRORID_BASE, 42)
D(IDS_ERRORID_MIDI_NOT_DEVICE_NAME,	IDS_ERRORID_BASE, 43)
D(IDS_ERRORID_MIDI_NOT_CONFIG_PROXY,	IDS_ERRORID_BASE, 44)
D(IDS_ERRORID_MIDI_DRIVER_VER_OK,	IDS_ERRORID_BASE, 45)
D(IDS_ERRORID_MIDI_DRIVER_VER_ERROR,	IDS_ERRORID_BASE, 46)
D(IDS_ERRORID_MIDI_SEND_BAD_VALUES,	IDS_ERRORID_BASE, 47)
D(IDS_ERRORID_MIDI_NOT_DRIVER,		IDS_ERRORID_BASE, 48)
D(IDS_ERRORID_MIDI_EMPTY_DRIVER,	IDS_ERRORID_BASE, 49)
D(IDS_ERRORID_MIDI_PROXY_PORTS,		IDS_ERRORID_BASE, 50)
D(IDS_ERRORID_MIDI_PROXY_OFF,		IDS_ERRORID_BASE, 51)
D(IDS_ERRORID_MIDI_OUT_PORTS,		IDS_ERRORID_BASE, 52)
D(IDS_ERRORID_MIDI_OUT_OFF,		IDS_ERRORID_BASE, 53)

/* Common::MMKey */
D(IDS_ERRORID_MMKEY_START,		IDS_ERRORID_BASE, 54)
D(IDS_ERRORID_MMKEY_STOP,		IDS_ERRORID_BASE, 55)

/* Common::MQTT */
D(IDS_ERRORID_MQTT_EMPTY_CONFIG,	IDS_ERRORID_BASE, 56)
D(IDS_ERRORID_MQTT_CLIENT_ERROR,	IDS_ERRORID_BASE, 57)
D(IDS_ERRORID_MQTT_CLIENT_OK,		IDS_ERRORID_BASE, 58)
D(IDS_ERRORID_MQTT_CONNECTED,		IDS_ERRORID_BASE, 59)
D(IDS_ERRORID_MQTT_NOT_CONNECTED,	IDS_ERRORID_BASE, 60)
D(IDS_ERRORID_MQTT_DISCONNECTED,	IDS_ERRORID_BASE, 61)
D(IDS_ERRORID_MQTT_NOT_CA_CERT,		IDS_ERRORID_BASE, 62)
D(IDS_ERRORID_MQTT_START,		IDS_ERRORID_BASE, 63)
D(IDS_ERRORID_MQTT_STOP,		IDS_ERRORID_BASE, 64)
D(IDS_ERRORID_MQTT_CA_FILTER,		IDS_ERRORID_BASE, 65)

/* Common::MIDIMT log level */
D(IDS_ERRORID_LOG_LEVEL_NONE,		IDS_ERRORID_BASE, 66)
D(IDS_ERRORID_LOG_LEVEL_INFO,		IDS_ERRORID_BASE, 67)
D(IDS_ERRORID_LOG_LEVEL_NOTICE,		IDS_ERRORID_BASE, 68)
D(IDS_ERRORID_LOG_LEVEL_WARNING,	IDS_ERRORID_BASE, 69)
D(IDS_ERRORID_LOG_LEVEL_ERR,		IDS_ERRORID_BASE, 70)
D(IDS_ERRORID_LOG_LEVEL_DEBUG,		IDS_ERRORID_BASE, 71)

/* Common::MIDIMT Audio PANEL */
D(IDS_ERRORID_PANEL_INDEX,		IDS_ERRORID_BASE, 72)
D(IDS_ERRORID_PANEL_INIT,		IDS_ERRORID_BASE, 73)
D(IDS_ERRORID_PANEL_ENABLE,		IDS_ERRORID_BASE, 74)
D(IDS_ERRORID_PANEL_NOT_UI_THREAD,	IDS_ERRORID_BASE, 75)
D(IDS_ERRORID_PANEL_NOT_ITEM_VALID,	IDS_ERRORID_BASE, 76)

/* Common::LIGHT::DMX */
D(IDS_ERRORID_LIGHT_DMX_START,		IDS_ERRORID_BASE, 77)
D(IDS_ERRORID_LIGHT_DMX_NOT_COM,	IDS_ERRORID_BASE, 78)
D(IDS_ERRORID_LIGHT_DMX_NOT_CONFIG,	IDS_ERRORID_BASE, 79)
D(IDS_ERRORID_LIGHT_DMX_STOP,		IDS_ERRORID_BASE, 80)
D(IDS_ERRORID_LIGHT_DMX_NODEV,		IDS_ERRORID_BASE, 81)
D(IDS_ERRORID_LIGHT_DMX_SELDEV,		IDS_ERRORID_BASE, 82)

/* Common::LIGHT::ArtNet */
D(IDS_ERRORID_LIGHT_ARTNET_START,	IDS_ERRORID_BASE, 83)
D(IDS_ERRORID_LIGHT_ARTNET_NOT_IFACE,	IDS_ERRORID_BASE, 84)
D(IDS_ERRORID_LIGHT_ARTNET_NOT_CONFIG,	IDS_ERRORID_BASE, 85)
D(IDS_ERRORID_LIGHT_ARTNET_STOP,	IDS_ERRORID_BASE, 86)
D(IDS_ERRORID_LIGHT_ARTNET_NOINT,	IDS_ERRORID_BASE, 87)
D(IDS_ERRORID_LIGHT_ARTNET_SELINT,	IDS_ERRORID_BASE, 88)

/* Common::IO::Plugins */
D(IDS_ERRORID_NOT_CLSID_CONVERT,	IDS_ERRORID_BASE, 89)
D(IDS_ERRORID_BRIDGE_NOT_INIT,		IDS_ERRORID_BASE, 90)
D(IDS_ERRORID_BRIDGE_NOT_LOAD,		IDS_ERRORID_BASE, 91)
D(IDS_ERRORID_BRIDGE_OK_INIT_LOAD,	IDS_ERRORID_BASE, 92)
D(IDS_ERRORID_BRIDGE_OK_START,		IDS_ERRORID_BASE, 93)
D(IDS_ERRORID_BRIDGE_NOT_START,		IDS_ERRORID_BASE, 94)
D(IDS_ERRORID_BRIDGE_OK_STOP,		IDS_ERRORID_BASE, 95)
D(IDS_ERRORID_BRIDGE_NOT_STOP,		IDS_ERRORID_BASE, 96)
D(IDS_ERRORID_PLUGIN_ALREADY_LOADED,	IDS_ERRORID_BASE, 97)
D(IDS_ERRORID_PLUGIN_ALREADY_STARTED,	IDS_ERRORID_BASE, 98)
D(IDS_ERRORID_PLUGIN_ALREADY_STOPED,	IDS_ERRORID_BASE, 99)
D(IDS_ERRORID_PLUGIN_DLL_ERROR,		IDS_ERRORID_BASE, 100)
D(IDS_ERRORID_PLUGIN_DLL_NOT_PLUGIN,	IDS_ERRORID_BASE, 101)
D(IDS_ERRORID_PLUGIN_LIST_INFO,		IDS_ERRORID_BASE, 102)

/* Common::MIDIMT */
D(IDS_ERRORID_MIDIMT_UPCONFIG,		IDS_ERRORID_BASE, 103)
D(IDS_ERRORID_MIDIMT_NOPLUGINS,		IDS_ERRORID_BASE, 104)
D(IDS_ERRORID_MIDIMT_CONFEDIT,		IDS_ERRORID_BASE, 105)
D(IDS_ERRORID_MIDIMT_CONFFILTER,	IDS_ERRORID_BASE, 106)
D(IDS_ERRORID_MIDIMT_EXEFILTER,		IDS_ERRORID_BASE, 107)
D(IDS_ERRORID_MIDIMT_JSONFILTER,	IDS_ERRORID_BASE, 108)
D(IDS_ERRORID_MIDIMT_CONFFROMFILE,	IDS_ERRORID_BASE, 109)
D(IDS_ERRORID_MIDIMT_CONFFROMDRV,	IDS_ERRORID_BASE, 110)
D(IDS_ERRORID_MIDIMT_LANG_ACTIVE,	IDS_ERRORID_BASE, 111)
D(IDS_ERRORID_MIDIMT_VDRV_VERSION,	IDS_ERRORID_BASE, 112)

/* Common::Remote */
D(IDS_ERRORID_REMOTE_START,		IDS_ERRORID_BASE, 113)
D(IDS_ERRORID_REMOTE_STOP,		IDS_ERRORID_BASE, 114)
D(IDS_ERRORID_REMOTE_CLIENT_NEW,	IDS_ERRORID_BASE, 115)
D(IDS_ERRORID_REMOTE_CLIENT_ERR,	IDS_ERRORID_BASE, 116)
D(IDS_ERRORID_REMOTE_CLIENT_CLOSE,	IDS_ERRORID_BASE, 117)

/* Common::JOISTICK */
D(IDS_ERRORID_JOY_NODRIVER,		IDS_ERRORID_BASE, 118)
D(IDS_ERRORID_JOY_INVALIDPARAM,		IDS_ERRORID_BASE, 119)
D(IDS_ERRORID_JOY_NOCANDO,		IDS_ERRORID_BASE, 120)
D(IDS_ERRORID_JOY_UNPLUGGED,		IDS_ERRORID_BASE, 121)
D(IDS_ERRORID_JOY_START,		IDS_ERRORID_BASE, 122)
D(IDS_ERRORID_JOY_STOP,			IDS_ERRORID_BASE, 123)
D(IDS_ERRORID_JOY_CHANGE_SCENE,		IDS_ERRORID_BASE, 124)
D(IDS_ERRORID_JOY_CHANGE_CTRL,		IDS_ERRORID_BASE, 125)

/* All other */
D(IDS_ERRORID_COPY_LINK,		IDS_ERRORID_BASE, 126)
D(IDS_ERRORID_NET_IFACE_NONE,		IDS_ERRORID_BASE, 127)
D(IDS_ERRORID_NET_IFACE_SELECT,		IDS_ERRORID_BASE, 128)
D(IDS_ERRORID_TIMEOUT_EXPIRED,		IDS_ERRORID_BASE, 129)

/* All other */
D(IDS_ERRORID_SCRIPT_ERROR,		IDS_ERRORID_BASE, 130)
D(IDS_ERRORID_SCRIPT_EMPTY,		IDS_ERRORID_BASE, 131)
D(IDS_ERRORID_SCRIPT_MODIFY,		IDS_ERRORID_BASE, 132)
D(IDS_ERRORID_SCRIPT_LOADED,		IDS_ERRORID_BASE, 133)
D(IDS_ERRORID_SCRIPT_NOTFOUND,		IDS_ERRORID_BASE, 134)
D(IDS_ERRORID_SCRIPT_START,		IDS_ERRORID_BASE, 135)
D(IDS_ERRORID_SCRIPT_STOP,		IDS_ERRORID_BASE, 136)
D(IDS_ERRORID_SCRIPT_DIRFILTER,		IDS_ERRORID_BASE, 137)
D(IDS_ERRORID_SCRIPT_CALL,		IDS_ERRORID_BASE, 138)
D(IDS_ERRORID_SCRIPT_RESCAN,		IDS_ERRORID_BASE, 139)
D(IDS_ERRORID_SCRIPT_STOPALL,		IDS_ERRORID_BASE, 140)

/* File Watcher */
D(IDS_ERRORID_FILEWATCH_OPEN,		IDS_ERRORID_BASE, 141)
D(IDS_ERRORID_FILEWATCH_PARAM,		IDS_ERRORID_BASE, 142)
D(IDS_ERRORID_FILEWATCH_SHUTDOWN,	IDS_ERRORID_BASE, 143)
D(IDS_ERRORID_FILEWATCH_NOACCESS,	IDS_ERRORID_BASE, 144)

/* err_NONE */
D(IDS_ERRORID_NONE,			IDS_ERRORID_BASE, 145)
