remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: [EasyControl MIDI Control Surfaces && Adobe Premiere Pro]
description: [EasyControl-MIDI Command Translator to MIDI-Mackie Working with Control Surfaces in Adobe Premiere Pro]

github:
    zip_url: https://github.com/ClaudiaCoord/MIDI-EasyControl-to-Mackie-translator-for-Premiere-Pro/releases/download/1.0.1.1/MIDIMT_x64.msi
    another_url: https://github.com/ClaudiaCoord/MIDI-EasyControl-to-Mackie-translator-for-Premiere-Pro/releases/download/1.0.1.1/MIDIMT_x86.msi
