//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется MIDIMT.rc
//
#define IDD_MIDIMT_DIALOG               101
#define IDD_FORMABOUT                   102
#define IDD_FORMSTART                   103
#define IDD_FORMMONITOR                 104
#define IDD_FORMSETUP                   105
#define IDD_FORMSMARTHOME		106
#define IDD_FORMCOLOR                   107
#define IDD_ASSIGNBOX			108

#define IDR_TRAY_MENU                   110
#define IDR_LV_MENU                     111
#define IDR_COL3_TYPE_MENU              112
#define IDR_COL4_ALL_TARGET_MENU        113
#define IDR_COL4_BTN_TARGET_MENU        114
#define IDR_COL4_SLIDER_TARGET_MENU     115
#define IDR_COL5_BTN_MIX_MENU           116
#define IDR_COL5_SLIDER_MIX_MENU        117
#define IDR_COL5_BTN_MMKEY_MENU         118
#define IDR_COL5_SLIDER_SM_MENU         119
#define IDR_COL5_BTN_SM_MENU            120
#define IDR_COL5_MENU_REPLACE_FIELD1    121
#define IDR_COL5_MENU_REPLACE_FIELD2    122
#define IDR_MIXER_CTRL_MENU             123

#define IDI_MIDIMT                      201
#define IDI_SMALL                       202
#define IDI_ICON_FOLDER                 203
#define IDI_ICON_RUNAPP                 204
#define IDI_ICON_REMOVE                 205
#define IDI_ICON_INFO			206
#define IDI_ICON_SOUNDON                207
#define IDI_ICON_SOUNDOFF               208
#define IDI_ICON_SETUP1                 209
#define IDI_ICON_SETUP2                 210
#define IDI_ICON_SETUP3                 211
#define IDI_ICON_LV1                    212
#define IDI_ICON_LV2                    213
#define IDI_ICON_LV3                    214
#define IDI_ICON_LV4                    215
#define IDI_ICON_LV5                    216
#define IDI_ICON_LV6                    217
#define IDI_ICON_MENUH_LIGHT            218
#define IDI_ICON_MENUH_DARK             219

#define IDB_KNOB_METRO_ENABLED          254
#define IDB_KNOB_METRO_DISABLED         255
#define IDB_KNOB_DARK_ENABLED           256
#define IDB_KNOB_DARK_DISABLED          257
#define IDB_KNOB_LIGHT_ENABLED          258
#define IDB_KNOB_LIGHT_DISABLED         259
#define IDB_KNOB_MODERN_ENABLED		260
#define IDB_KNOB_MODERN_DISABLED	261
#define IDB_KNOB_RETRO_ENABLED		262
#define IDB_KNOB_RETRO_DISABLED		263
#define IDC_MIDIMT                      300
#define IDS_INFO1                       301
#define IDS_INFO2                       302
#define IDS_INFO3                       303
#define IDS_INFO4                       304
#define IDS_INFO5                       305
#define IDS_INFO6                       306
#define IDS_INFO7                       307
#define IDS_INFO8                       308
#define IDS_INFO9                       309
#define IDS_INF1O                       310
#define IDS_INF11                       311
#define IDS_INF12                       312
#define IDS_INF13                       313
#define IDB_BMP_LOGO                    314
#define IDB_BMP_ASSIGN			315

#define IDC_DIALOG_SAVE                 998
#define IDC_DIALOG_EXPORT               999
#define IDC_OK2                         1001
#define IDC_MONITOR_CLEAR               1002
#define IDC_OK3                         1003
#define IDC_LOG                         1004
#define IDC_START_RADIO1                1005
#define IDC_START_RADIO2                1006
#define IDC_AUTOBOOT_SYS                1007
#define IDC_AUTORUN_SYS                 1008
#define IDC_AUTORUN_CONFIG              1009
#define IDC_MIXER_ENABLE                1010
#define IDC_MMKEY_ENABLE                1011
#define IDC_MANUALPORT_CONFIG           1012
#define IDC_JOGFILTER_CONFIG            1013
#define IDC_MIXER_FAST_VALUE            1014
#define IDC_MIXER_OLD_VALUE             1015
#define IDC_MIXER_DUPLICATE		1016
#define IDC_INFO_ISCONFIG               1017
#define IDC_WRITE_FILELOG               1018
#define IDC_EXIT_BUTTON                 1019
#define IDC_GO_ABOUT                    1020
#define IDC_GO_URL                      1021
#define IDC_GO_START                    1022
#define IDC_INFO_ISPROXY                1023
#define IDC_OPEN_CONFIG                 1024
#define IDC_INFO_ISUNITS                1025
#define IDC_DEVICE_COMBO                1030
#define IDC_PROXY_COMBO                 1031
#define IDC_MIDI_MACKIE_OUT             1032
#define IDC_MIDI_PROXY_OUT              1033
#define IDC_SLIDER_INT                  1034
#define IDC_SLIDER_LONGINT              1035
#define IDC_SLIDER_VAL1                 1036
#define IDC_SLIDER_VAL2                 1037
#define IDC_MIXER_RIGHT_CLICK           1038
#define IDC_MONITOR                     1039
#define IDC_FILE_CONFIG_NAME            1040
#define IDC_MONITOR_START               1041
#define IDC_INFO_CTRLCOUNT              1042
#define IDC_MONITOR_STOP                1043
#define IDC_LANG_COMBO                  1044
#define IDC_SETUP_CODE                  1045
#define IDC_SETUP_NUMBER                1046
#define IDC_SETUP_SCENE                 1047
#define IDC_SETUP_TYPE                  1048
#define IDC_SETUP_TARGET                1049
#define IDC_SETUP_TARGET_LONG           1050
#define IDC_SETUP_SCENEN                1051
#define IDC_SETUP_TYPEN                 1052
#define IDC_SETUP_TARGETN               1053
#define IDC_SETUP_TARGET_LONGN          1054
#define IDC_SETUP_COUNT                 1056
#define IDC_SETUP_LIST                  1057
#define IDC_SETUP_ICON                  1058
#define IDC_SETUP_HELPLIST              1059
#define IDC_SETUP_APPLIST               1060
#define IDC_INFO_VMDRV_CHECK            1061
#define IDC_INFO_VMDRV_VER              1062
#define IDC_SETUP_RADIO1                1063
#define IDC_SETUP_RADIO2                1064
#define IDC_SETUP_RADIO3                1065
#define IDC_SETUP_RADIO4                1066
#define IDC_BTN_FOLDER                  1067
#define IDC_BTN_RUNAPP                  1068
#define IDC_BTN_REMOVE                  1069
#define IDC_BTN_MUTE                    1070
#define IDC_BTN_INFO                    1071
#define IDC_SLIDER_VOLUME               1072
#define IDC_ABOUT_VERSION               1073
#define IDC_ABOUT_COPY                  1074
#define IDC_IEVENT_DATA                 1075
#define IDC_IEVENT_LOG                  1076
#define IDC_IEVENT_MONITOR              1077
#define IDC_IEVENT_BALLOON              1078
#define IDC_IEVENT_CLEAR		1079
#define IDC_COLOR_BOX1                  1080
#define IDC_COLOR_BOX2                  1081
#define IDC_COLOR_BOX3                  1082
#define IDC_RADIO_LIGHT			1083
#define IDC_RADIO_DARK			1084
#define IDC_RADIO_METRO			1085
#define IDC_RADIO_MODERN		1086
#define IDC_RADIO_RETRO			1087

#define IDC_MQTT_ENABLE                 1101
#define IDC_MQTT_IPADDR                 1102
#define IDC_MQTT_PORT                   1103
#define IDC_MQTT_LOGIN                  1104
#define IDC_MQTT_PASS                   1105
#define IDC_MQTT_PSK                    1106
#define IDC_MQTT_ISSSL                  1107
#define IDC_MQTT_ISSELFSIGN             1108
#define IDC_MQTT_CA                     1109
#define IDC_MQTT_CAOPEN                 1110
#define IDC_MQTT_PREFIX                 1111
#define IDC_MQTT_LOGLEVEL               1112

#define IDS_APP_TITLE                   3100
#define IDS_MIXER                       3101
#define IDS_SETTINGS                    3102
#define IDS_START                       3103
#define IDS_STOP                        3104
#define IDS_EXIT                        3105
#define IDS_SETUP_MSG1                  3106
#define IDS_SETUP_MSG2                  3107
#define IDS_SETUP_MSG3                  3108
#define IDS_URL_WIKI                    3109
#define IDS_URL_GIT                     3110
#define IDS_URL_WEB                     3111
#define IDS_URL_ESETUP			3112
#define IDS_START_EXT_FILTER            3113
#define IDS_CONFIG_EXE_FILTER           3114
#define IDS_MQTT_CA_FILTER		3115

#define IDS_DLG_MSG1                    3120
#define IDS_DLG_MSG2                    3121
#define IDS_DLG_MSG3                    3122
#define IDS_DLG_MSG4                    3123
#define IDS_DLG_MSG5                    3124
#define IDS_DLG_MSG6                    3125
#define IDS_DLG_MSG7                    3126
#define IDS_DLG_MSG8                    3127
#define IDS_DLG_MSG9                    3128
#define IDS_DLG_MSG10                   3129
#define IDS_DLG_MSG11                   3130
#define IDS_DLG_MSG12                   3131

#define IDM_CALLFORM_COLOR              32773
#define IDM_GO_ABOUT                    32774
#define IDM_GO_EMPTY                    32775
#define IDM_GO_INFO                     32776
#define IDM_GO_MIXER                    32777
#define IDM_GO_MONITOR                  32778
#define IDM_GO_SETUP                    32779
#define IDM_GO_START                    32780
#define IDM_GO_STOP                     32781
#define IDM_EXIT                        32782
#define IDM_LV_NEW                      32783
#define IDM_LV_COPY                     32784
#define IDM_LV_PASTE                    32785
#define IDM_LV_DELETE                   32786
#define IDM_LV_READ_MIDI_CODE           32787
#define IDM_LV_SET_MIXER                32788
#define IDM_LV_SET_MMKEY                32789
#define IDM_LV_SET_MQTT                 32790
#define IDM_LV_SET_NONE                 32791
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
