
#define IDI_MMENU_BASE		57000
#define IDI_MMENU_I0		(IDI_MMENU_BASE)
#define IDI_MMENU_I1		(IDI_MMENU_BASE + 1)
#define IDI_MMENU_I2		(IDI_MMENU_BASE + 2)
#define IDI_MMENU_I3		(IDI_MMENU_BASE + 3)
#define IDI_MMENU_I4		(IDI_MMENU_BASE + 4)
#define IDI_MMENU_I6		(IDI_MMENU_BASE + 6)
#define IDI_MMENU_I7		(IDI_MMENU_BASE + 7)
#define IDI_MMENU_I9		(IDI_MMENU_BASE + 9)

#define IDM_PLACE_BASE		58000
#define IDM_VERT_LEFT		(IDM_PLACE_BASE)
#define IDM_VERT_RIGHT		(IDM_PLACE_BASE + 1)
#define IDM_HOR_TOP		(IDM_PLACE_BASE + 2)
#define IDM_HOR_BOTTOM		(IDM_PLACE_BASE + 3)

#define IDM_THEME_BASE		59000
#define IDM_LIGHT		(IDM_THEME_BASE)
#define IDM_DARK		(IDM_THEME_BASE + 1)
#define IDM_METRO		(IDM_THEME_BASE + 2)
#define IDM_MODERN		(IDM_THEME_BASE + 3)
#define IDM_RETRO		(IDM_THEME_BASE + 4)
#define IDM_CUSTOM		(IDM_THEME_BASE + 5)
#define IDM_SAVE_POS		(IDM_THEME_BASE + 6)
#define IDM_CLOSE		(IDM_THEME_BASE + 7)
#define IDM_CUSTOM_RELOAD	(IDM_THEME_BASE + 8)
