
#ifndef Commonrcresource_error_enumh
#define Commonrcresource_error_enumh 1

/*
 * Part of MIDI-MT build
 * DO NOT EDIT THIS FILE!
 * EDIT ORIGINAL: Common\rc\template\resource_error_id_template.h
 */


#pragma once

namespace Common {

	enum class FLAG_EXPORT common_error_id : int {
		err_BASE = 55000,
		err_OK = 0,
		err_EMPTY = 1,
		err_UNDEFINED = 2,
		err_JSONCONF_WRITE_ACCESS = 3,
		err_JSONCONF_READ_ACCESS = 4,
		err_JSONCONF_EMPTY = 5,
		err_JSONCONF_NO_DEVICE = 6,
		err_JSONCONF_EMPTY_KEYS = 7,
		err_JSONCONF_WRITE_EMPTY = 8,
		err_INIT_COINITIALIZE = 9,
		err_INIT_COCREATE = 10,
		err_INIT_DEFAULT_AE = 11,
		err_INIT_AS_MANAGER2 = 12,
		err_INIT_AS_AUDIOMETER = 13,
		err_MIXER_STARTOK = 14,
		err_MIXER_STARTERROR = 15,
		err_MIXER_STOPOK = 16,
		err_MIXER_STOPERROR = 17,
		err_NO_INIT = 18,
		err_SESSION_LIST = 19,
		err_LISTISNULL = 20,
		err_SESSIONDISCONNECTED = 21,
		err_SESSIONCREATED = 22,
		err_ITEM_SC_AE = 23,
		err_CBVALUE_BAD_SELECT = 24,
		err_SET_CB_WARNING = 25,
		err_CONFIG_FAIL = 26,
		err_CONFIG_LOAD = 27,
		err_CONFIG_LOADA = 28,
		err_CONFIG_EMPTY = 29,
		err_CONFIG_NEW = 30,
		err_NOT_IMPLEMENTED = 31,
		err_NOT_CONFIG = 32,
		err_NOT_DEVICES = 33,
		err_COUNT_DEVICES = 34,
		err_OPEN_MIDI_DEVICE = 35,
		err_START_MIDI_DEVICE = 36,
		err_DEVICE_NOT_CONNECT = 37,
		err_DEVICE_FOUND = 38,
		err_DEVICE_OPEN = 39,
		err_DEVICE_CLOSE = 40,
		err_DEVICE_DONE = 41,
		err_NOT_DEVICE_NAME = 42,
		err_NOT_CONFIG_PROXY = 43,
		err_DRIVER_VER_OK = 44,
		err_DRIVER_VER_ERROR = 45,
		err_SEND_BAD_VALUES = 46,
		err_MMKEY_START = 47,
		err_MMKEY_STOP = 48,
		err_MQTT_EMPTY_CONFIG = 49,
		err_MQTT_CLIENT_ERROR = 50,
		err_MQTT_CLIENT_OK = 51,
		err_MQTT_CONNECTED = 52,
		err_MQTT_NOT_CONNECTED = 53,
		err_MQTT_DISCONNECTED = 54,
		err_MQTT_NOT_CA_CERT = 55,
		err_MQTT_START = 56,
		err_MQTT_STOP = 57,
		err_PANEL_INDEX = 58,
		err_PANEL_INIT = 59,
		err_PANEL_ENABLE = 60,
		err_PANEL_NOT_UI_THREAD = 61,
		err_PANEL_NOT_ITEM_VALID = 62,
		err_NONE = 63,

	};
}

#endif

