
#ifndef Commonrcresource_midimth
#define Commonrcresource_midimth 1

/*
 * Part of MIDI-MT build
 * DO NOT EDIT THIS FILE!
 * EDIT ORIGINAL: Common\rc\template\resource_midimt_template.h
 */

#define IDM_MQTT_LOG_BASE		56000
#define IDM_MQTT_LOG_NONE		56000
#define IDM_MQTT_LOG_INFO		56001
#define IDM_MQTT_LOG_NOTICE		56002
#define IDM_MQTT_LOG_WARNING		56003
#define IDM_MQTT_LOG_ERR		56004
#define IDM_MQTT_LOG_DEBUG		56005
#define IDI_MMENU_BASE		57000
#define IDI_MMENU_I0		57000
#define IDI_MMENU_I1		57001
#define IDI_MMENU_I2		57002
#define IDI_MMENU_I3		57003
#define IDI_MMENU_I4		57004
#define IDI_MMENU_I6		57006
#define IDI_MMENU_I7		57007
#define IDI_MMENU_I9		57009
#define IDM_PLACE_BASE		58000
#define IDM_VERT_LEFT		58000
#define IDM_VERT_RIGHT		58001
#define IDM_HOR_TOP		58002
#define IDM_HOR_BOTTOM		58003
#define IDM_THEME_BASE		59000
#define IDM_LIGHT		59000
#define IDM_DARK		59001
#define IDM_METRO		59002
#define IDM_MODERN		59003
#define IDM_RETRO		59004
#define IDM_CUSTOM		59005
#define IDM_SAVE_POS		59006
#define IDM_CLOSE		59007
#define IDM_ANIMATION		59008
#define IDM_APP_PATH		59009
#define IDM_MIDI_BIND		59010
#define IDM_PEAK_METER		59011
#define IDM_CUSTOM_RELOAD		59012

#endif

