//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется MIDIMT.rc
//
#define IDD_MIDIMT_DIALOG               101
#define IDD_FORMABOUT                   102
#define IDD_FORMSTART                   103
#define IDD_FORMMONITOR                 104
#define IDD_FORMSETUP                   105
#define IDR_MENU1                       155
#define IDR_LV_MENU                     155
#define IDI_MIDIMT                      201
#define IDI_SMALL                       202
#define IDC_MIDIMT                      300
#define IDS_INFO1                       301
#define IDS_INFO2                       302
#define IDS_INFO4                       303
#define IDS_INFO5                       304
#define IDS_INFO3                       305
#define IDR_TRAY_MENU                   306
#define IDB_BMP_LOGO                    307
#define IDB_ICON1                       308
#define IDB_ICON2                       309
#define IDB_ICON3                       310
#define IDB_ICON4                       311
#define IDB_ICON5                       312
#define IDB_ICON6                       313
#define IDB_ICON7                       314
#define IDB_ICON_SETUP1                 315
#define IDB_ICON_SETUP2                 316
#define IDB_ICON_SETUP3                 317
#define IDC_CONFIG_SAVE                 1000
#define IDC_OK2                         1001
#define IDC_MONITOR_CLEAR               1002
#define IDC_OK3                         1003
#define IDC_LOG                         1009
#define IDC_RADIO1                      1010
#define IDC_RADIO2                      1011
#define IDC_CHECK1                      1012
#define IDC_CHECK2                      1013
#define IDC_CHECK3                      1014
#define IDC_CHECK4                      1015
#define IDC_CHECK5                      1016
#define IDC_CHECK6                      1017
#define IDC_CHECK7                      1018
#define IDC_CHECK8                      1019
#define IDC_CHECK9                      1020
#define IDC_CHECK12                     1021
#define IDC_WRITELOG_CHECK              1022
#define IDC_EXIT_BUTTON                 1023
#define IDC_AUTOBOOT_CHECK              1024
#define IDC_GO_ABOUT                    1025
#define IDC_GO_URL                      1026
#define IDC_GO_START                    1027
#define IDC_DEVICE_COMBO                1030
#define IDC_PROXY_COMBO                 1031
#define IDC_MIDI_MACKIE_OUT             1032
#define IDC_MIDI_PROXY_OUT              1033
#define IDC_SLIDER_INT                  1034
#define IDC_SLIDER_LONGINT              1035
#define IDC_SLIDER_VAL1                 1036
#define IDC_SLIDER_VAL2                 1037
#define IDC_MONITOR                     1038
#define IDC_MONITOR_START               1039
#define IDC_MONITOR_STOP                1040
#define IDC_SETUP_CODE                  1041
#define IDC_SETUP_NUMBER                1042
#define IDC_SETUP_SCENE                 1043
#define IDC_SETUP_TYPE                  1044
#define IDC_SETUP_TARGET                1045
#define IDC_SETUP_TARGET_LONG           1046
#define IDC_SETUP_SCENEN                1047
#define IDC_SETUP_TYPEN                 1048
#define IDC_SETUP_TARGETN               1049
#define IDC_SETUP_TARGET_LONGN          1050
#define IDC_SETUP_SAVE                  1051
#define IDC_SETUP_COUNT                 1052
#define IDC_SETUP_LIST                  1053
#define IDC_SETUP_ICON                  1054
#define IDC_SETUP_MSG                   1055
#define IDC_SETUP_HELPLIST              1056
#define IDS_APP_TITLE                   3100
#define IDS_SETTINGS                    3101
#define IDS_START                       3102
#define IDS_STOP                        3103
#define IDS_EXIT                        3104
#define IDS_DLG_MSG1                    3105
#define IDS_DLG_MSG2                    3106
#define IDS_SETUP_MSG1                  3107
#define IDS_SETUP_MSG2                  3108
#define IDS_SETUP_MSG3                  3109
#define IDM_GO_ABOUT                    32774
#define IDM_GO_INFO                     32775
#define IDM_GO_START                    32776
#define IDM_GO_STOP                     32777
#define IDM_EXIT                        32778
#define IDM_GO_MONITOR                  32779
#define IDM_GO_SETUP                    32780
#define IDM_GO_EMPTY                    32781
#define IDM_LV_NEW                      32782
#define IDM_LV_COPY                     32783
#define IDM_LV_PASTE                    32784
#define IDM_LV_DELETE                   32785
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
